= Agregar un nuevo estándar

WARNING: Esta página contiene instrucciones de configuración solo para usuarios avanzados de IPT 

El IPT siempre se instala con 3 clases del estándar Darwin Core cargados de forma predeterminada: "taxon", "occurrence" y "event". Desde la versión 2.1 de IPT, existe la posibilidad de agregar clases personalizadas, lo que es útil para las comunidades que crean prototipos de nuevos estándares de datos. De esta manera, su comunidad puede comenzar a intentar mapear sus datos al nuevo estándar y refinar iterativamente su conjunto de propiedades.

Los 3 pasos siguientes explican cómo

. crear su nuevo núcleo,
. registrarlo en GBIF, y
. configurar un IPT para utilizarlo.

== Instrucciones

. *Escribir la definición del núcleo XML*
+
La definición XML del núcleo debe cumplir con el http://rs.gbif.org/schema/extension.xsd[GBIF Extension Schema]. Es más fácil simplemente adaptar una definición de núcleo existente, como {latest-dwc-occurrence}.xml[Darwin Core Occurrence Core]. Tenga en cuenta que la definición principal debe contener una propiedad que sirva como identificador de registro (por ejemplo, http://rs.tdwg.org/dwc/terms/occurrenceID para el núcleo de la ocurrencia, o http://rs.tdwg.org/dwc/terms/eventID para Event Core. El proceso de creación de una nueva extensión no principal es exactamente el mismo que para una extensión principal. El proceso de creación de un nuevo vocabulario (como un tipo de datos para una propiedad dentro del núcleo, o no -core) es diferente solo en que la definición XML tiene que cumplir con el http://rs.gbif.org/schema/thesaurus.xsd[GBIF Thesaurus Schema]. Una vez más, es más fácil adaptar una definición de vocabulario existente, como la {latest-basis-of-record}[Vocabulario de Darwin Core Type].

. *Registrar el núcleo con GBIF*
+
Si bien la definición del núcleo aún está experimentando cambios, se registra en GBIF Sandbox Registry. Para registrar su núcleo, realice una solicitud de extracción al repositorio rs.gbif.org siguiendo https://github.com/gbif/rs.gbif.org/blob/master/versioning.md#how-to-create-a-new-version-of-an-extension-or-vocabulary-on-rsgbiforg[estas instrucciones]. Si pasa la inspección, se fusionará con https://rs.gbif.org/sandbox/core/ y se incluirá en la https://gbrdsdev.gbif.org/registry/extensions.json[Lista de Sandbox Registry de extensiones]. Cuando se haya finalizado la definición principal, lo que significa que su conjunto de propiedades se ha congelado, se alojará en https://rs.gbif.org/core/ y se incluirá en https://gbrds.gbif.org/registry/extensions.json[Lista de extensiones de Live Registry] El mismo proceso se aplica al registro de extensiones y vocabularios secundarios.

. *Configurar el IPT*
+
--
Para configurar el IPT para usar el {sandbox-material-sample}[Material de ejemplo del núcleo], por ejemplo, agregue las 2 líneas siguientes a `$IPT_DATA_DIR/config/ipt.properties`.

NOTE: asegúrese de escapar todos los dos puntos como antes*

----
ipt.core_rowTypes=http\://rs.tdwg.org/dwc/terms/MaterialSample
ipt.core_idTerms=http\://rs.tdwg.org/dwc/terms/materialSampleID
----

Esto configura el IPT para reconocer todas las extensiones con rowType http://rs.tdwg.org/dwc/terms/MaterialSample como tipos principales y para usar http://rs.tdwg.org/dwc/terms/materialSampleID como su identificador término. Se pueden especificar varios núcleos, delimitándolos con el carácter de barra vertical `|` (pipe). La primera entrada de ipt.core_idTerms es el ID de la primera entrada de core_rowTypes, y así sucesivamente. Por último, guarde el archivo ipt.properties, reinicie Tomcat y luego xref:Administration.adoc#install-extension[instalar el núcleo]. El núcleo ahora está disponible para su uso en el IPT.
--
