= Centros de alojamiento de datos

== Introducción

Un centro de alojamiento de datos (DHC) le proporciona una cuenta en su IPT, lo que le permite administrar sus propios conjuntos de datos y publicarlos a través de https://www.gbif.org[GBIF.org].

Se recomienda ampliamente el uso de un DHC debido a que le ahorrará tiempo y dinero al configurar su propia instancia de IPT y podrá recibir servicio de asistencia técnica en su idioma.

Utilice esta página para encontrar un DHC de confianza por país o por tema que sea adecuado para usted. Si no existe un DHC adecuado o el DHC no responde rápidamente su consulta, comuníquese con mailto:helpdesk@gbif.org[GBIF Helpdesk] para obtener ayuda.

Tenga en cuenta que para calificar como un DHC de confianza, el centro debe cumplir con un estricto conjunto de criterios. De esta manera, puede confiar en que el DHC mantendrá su IPT en línea cerca del 100% del tiempo, y se asegurarán de que se haga una copia de seguridad de su conjunto de datos.

== Criterios del centro de alojamiento de datos

Un DHC debe cumplir con el siguiente conjunto de requisitos estrictos para ser recomendado a los publicadores:

* Su IPT está en línea casi el 100% del tiempo
* Pueden administrar adecuadamente su IPT:
** Manteniéndolo actualizado con la última versión
** Asegurando que el directorio de datos del IPT se respalde de manera regular
** Administrando las cuentas de usuario
** Administrando las extensiones y estándares
* Tienen un historial comprobado de alojamiento de datos para publicadores en su país.
* Pueden proporcionar asistencia técnica rápida y con conocimientos:
** Saben cómo usar el IPT para publicar datos a través de GBIF.org
** Conocen los estándares de datos de biodiversidad en general
** Saben cómo publicar artículos

Si cree que su DHC cumple con estos estándares y le gustaría ofrecer sus servicios a los editores de su país, envíe un correo electrónico a mailto: helpdesk@gbif.org.

== Centros de alojamiento de datos por tema

* <<Datos dulceacuícolas>>
* <<Datos marinos>>
* <<Datos de vertebrados>>

== Centros de alojamiento de datos por ubicación

* <<Bélgica>>
* <<Canadá>> ⭐
* <<Colombia>> ⭐
* <<Dinamarca>>
* <<Finlandia>>
* <<Francia>> (también para Benín, Botswana, Burkina Faso, Camerún, Costa de Marfil, Gabón, Ghana, Guinea, Madagascar, Nigeria, Senegal, Togo y Uganda)
* <<Noruega>>
* <<Portugal>>
* <<Sudáfrica>>
* <<España>> ⭐
* <<Suecia>>
* <<Taiwán>>
* <<EUA>>

⭐Designa a un país con un IPT que actúa como repositorio, capaz de asignar DOI a conjuntos de datos de publicaciones científicas en revistas como https://www.nature.com/sdata/[Datos científicos].

== Bélgica

La https://www.biodiversity.be[Plataforma de Biodiversidad de Bélgica] proporciona asistencia técnica a los publicadores en Bélgica y soporte de alojamiento para conjuntos de datos en https://ipt.biodiversity.be/[Belgian BIF IPT]. Póngase en contacto con André Heughebaert <a.heughebaert@biodiversity.be> para obtener ayuda. La plataforma de Biodiversidad belga comparte su IPT con las siguientes organizaciones:

* http://www.naturalsciences.be[Real Instituto Belga de Ciencias Naturales]
* http://www.ulg.be[Universidad de Lieja]
* http://www.plantentuinmeise.be[Jardín Botánico Meise]
* http://biodiversite.wallonie.be[Servicio Público de Valonia - Departamento de Estudios Naturales y Agrícolas (SPW - DEMNA)]
* http://www.portail.umons.ac.be[Universidad de Mons-Hainaut]
* http://www.ulb.ac.be/[Universidad Libre de Bruselas ]
* http://www.africamuseum.be[Museo Real de África central, Bélgica]
* http://www.ugent.be[Universidad de Gante]
* https://www.natagriwal.be/[Natagriwal]
* https://www.itg.be/[Instituto de Medicina Tropical de Amberes]

La Plataforma de Biodiversidad de Bélgica también alberga un IPT para cada uno de estos países/instituciones:

* http://ipt-mrbif.bebif.be/[IPT GBIF Mauritania]
* http://ipt.biodiversity.aq/[IPT Antabif]
* http://data.freshwaterbiodiversity.eu/ipt/[IPT Biofresh]

El Instituto de Investigación para la Naturaleza y los Bosques (INBO) también proporciona soporte de alojamiento para conjuntos de datos que se originan en la región flamenca http://data.inbo.be/ipt[IPT] . El INBO está compartiendo su instancia de IPT con estas organizaciones:

* http://www.natuurpunt.be[Natuurpunt]
* http://www.vmm.be[Agencia Flamenca de Medio Ambiente VMM]

El Instituto Marino Flanders (VLIZ) aloja un servidor con múltiples instalaciones del IPT para http://www.vliz.be[VLIZ], http://www.iobis.org[OBIS] y http://www.emodnet-biology.eu [EMODnet Biology] en http://ipt.vliz.be. Los publicadores de datos marinos deben consultar la sección <<Datos marinos>>.

== Canadá

El http://www.cbif.gc.ca/[Servicio Canadiense de Información sobre Biodiversidad (CBIF)] no ejecuta un IPT.

Por lo tanto, se recomienda que se comunique con a Canadensys, que brinda ayuda técnica a los publicadores nuevos en Canadá, y soporte de alojamiento para conjuntos de datos http://data.canadensys.net/ipt[IPT Canadensys]. Contacte a Canadensys <canadensys.network@gmail.com> para obtener ayuda.

El http://data.canadensys.net/ipt[IPT Canadensys] se reconoce como un repositorio en https://fairsharing.org/biodbcore-000855[FAIRSharing.org]. Un número cada vez mayor de revistas dirige a los autores a un repositorio apropiado en FAIRSharing.org para garantizar que los datos de las publicaciones científicas se depositen de manera estandarizada.

== Colombia

El http://www.sibcolombia.net/[Sistema de Información de Biodiversidad Colombiano (SiB Colombia)] proporciona servicio de soporte técnico a los publicadores nuevos en Colombia y soporte de alojamiento de conjuntos de datos en http://ipt.sibcolombia.net/sib/[IPT SiB Colombia]. Contacte al SiB Colombia <sib@humboldt.org.co> para obtener ayuda.

El http://ipt.sibcolombia.net/sib/[IPT SiB Colombia] se reconoce como un repositorio en https://fairsharing.org/biodbcore-000856[FAIRSharing.org]. Un número cada vez mayor de revistas dirige a los autores a un repositorio apropiado en FAIRSharing.org para garantizar que los datos de las publicaciones científicas se depositen de manera estandarizada.

== Dinamarca

El http://danbif.dk/[Servicio Danés de Información sobre Biodiversidad (DanBIF)] brinda soporte técnico a los nuevos publicadores en Dinamarca y soporte de alojamiento para conjuntos de datos en http://danbif.au.dk/ipt/[IPT DanBIF]. Comuníquese con DanBIF <icalabuig@snm.ku.dk> para obtener ayuda.

== Finlandia

El Servicio Finlandés de Información sobre Biodiversidad (FinBIF) (https://laji.fi/) brinda soporte técnico a los nuevos publicadores en Finlandia y soporte de alojamiento para conjuntos de datos en el IPT de FinBIF (https://ipt.laji.fi/ipt). Comuníquese con FinBIF eija-leena.laiho@helsinki.fi para obtener ayuda.

== Francia

http://www.gbif.fr/[GBIF Francia] proporciona asistencia técnica a los nuevos publicadores y aloja un IPT para cada uno de estos países:

* http://ipt-benin.gbif.fr[IPT de GBIF Benín]
* http://ipt-botswana.gbif.fr/[IPT de Botswana] - _Nota Botswana no es participante de GBIF_
* http://ipt-burkinafaso.gbif.fr[IPT de Burkina Faso] - _Nota Burkina Faso no es participante de GBIF_
* http://ipt-cameroun.gbif.fr[IPT de Camerún]
* http://ipt-cotedivoire.gbif.fr[IPT de Costa de Marfil] - _Nota Costa de Marfil no es un Participante GBIF_
* http://ipt.gbif.fr[IPT de GBIF Francia]
* http://ipt-gabon.gbif.fr[IPT de Gabón] - _Nota Gabón no es un participante de GBIF_
* http://ipt-ghana.gbif.fr[IPT de Ghana BIF]
* http://ipt-guinee.gbif.fr[IPT de GBIF Guinea]
* http://ipt-inpn.gbif.fr/[IPT de INPN]
* http://ipt.madbif.mg[IPT de Madagascar MadBIF]
* http://ipt-nigeria.gbif.fr[IPT de GBIF Nigeria]
* http://ipt-senegal.gbif.fr[IPT de Senegal] - _Nota Senegal no es un participante de GBIF_
* http://ipt-togo.gbif.fr[IPT de GBIF Togo]
* http://ipt-uganda.gbif.fr[IPT de GBIF Uganda]

Póngase en contacto con GBIF-Francia <gbif@gbif.fr> para obtener ayuda. Para problemas técnicos, escriba a <dev@gbif.fr>.

== Noruega

http://www.gbif.no/[GBIF Noruega] proporciona asistencia técnica a los nuevos publicadores en Noruega y soporte de alojamiento para conjuntos de datos en http://ipt.gbif.no/[IPT de GBIF Noruega]. Póngase en contacto con GBIF Noruega <helpdesk@gbif.no> para obtener ayuda.

== Portugal

http://www.gbif.pt/[GBIF Portugal] proporciona asistencia técnica a los nuevos publicadores en Portugal y soporte de alojamiento para conjuntos de datos en http://ipt.gbif.pt[IPT de GBIF Portugal]. Póngase en contacto con GBIF Portugal <node@gbif.pt> para obtener ayuda.

== Sudáfrica

El http://www.sanbi.org/[Instituto Nacional de Biodiversidad de Sudáfrica (SANBI)] proporciona soporte técnico a nuevos publicadores en Sudáfrica y soporte de alojamiento para conjuntos de datos en http://197.189.235.147:8080/iptsanbi/[IPT del SANBI]. Póngase en contacto con <f.ramwashe@sanbi.org.za> para obtener ayuda.

== España

http://www.gbif.pt/[GBIF España] proporciona asistencia técnica a los nuevos publicadores en España y soporte de alojamiento para conjuntos de datos en http://www.gbif.es/ipt/[IPT de GBIF España]. Póngase en contacto con GBIF España <info@gbif.es> para obtener ayuda.

El http://www.gbif.es/ipt/[IPT de GBIF España] se reconoce como un repositorio en https://fairsharing.org/biodbcore-000854[FAIRSharing.org]. Un número cada vez mayor de revistas dirige a los autores a un repositorio apropiado en FAIRSharing.org para garantizar que los datos de las publicaciones científicas se depositen de manera estandarizada.

== Suecia

http://www.gbif.se/[GBIF Suecia] proporciona asistencia técnica a los nuevos publicadores en España y soporte de alojamiento para conjuntos de datos http://www.gbif.se/ipt/[IPT de GBIF Suecia]. Póngase en contacto con Anders Telenius <anders.telenius@nrm.se> para obtener ayuda.

== Taiwán

El http://www.taibif.tw/[El servicio de Información sobre Biodiversidad de Taiwán (TaiBIF)] brinda soporte técnico a los nuevos publicadores en Taiwán y soporte de alojamiento para conjuntos de datos en http://ipt.taibif.tw/[IP de TaiBIF]. Comuníquese con Melissa Liu <melissaliu0520@gmail.com> para obtener ayuda.

== EUA

El http://ipt.idigbio.org[IPT de iDigBio] proporciona soporte técnico a los nuevos publicadores de datos en los Estados Unidos y recursos de publicación de datos para conjuntos de datos que necesitan soporte para la movilización de datos. Póngase en contacto con data@idigbio.org para obtener ayuda.

http://vertnet.org/[VertNet] proporciona servicio de asistencia técnica a las instituciones que tienen vertebrados en uno o más de los conjuntos de datos que desean publicar. En otras palabras, si la institución está interesada en publicar conjuntos de datos de vertebrados (ya sean especímenes u observaciones), VertNet ayudará a publicar todos sus conjuntos de datos. Esto promueve la eficiencia al brindar y mantener el apoyo a la institución.

El http://www.usgs.gov/[Investigación geológica de los Estados Unidos (USGS)] brinda asistencia técnica a los nuevos publicadores en los Estados Unidos asociados o afiliados con el USGS o el gobierno federal de los EE. UU., y soporte de alojamiento para conjuntos de datos en https://bison.usgs.gov/ipt[IPT de USGS BISON]. Comuníquese con <bison@usgs.gov> para obtener ayuda. También tenga en cuenta que el USGS aloja IPT para las siguientes organizaciones/recursos: 

* https://www1.usgs.gov/obis-usa/ipt/[Sistema de Información Biogeográfica de los Océanos de EU OBIS-USA]
* https://nas.er.usgs.gov/ipt/[Recurso de información de las Especies acuáticas no endémicas (NAS) para el USGS]
* https://bison.usgs.gov/ipt[IPT de USGS-Información sobre biodiversidad al servicio de nuestra nación (BISON)]

== Datos dulceacuícolas

http://data.freshwaterbiodiversity.eu/ipt/[Biofresh] proporciona alojamiento de datos y servicio de asistencia técnica a los publicadores de datos de agua dulce de todo el mundo en http://data.freshwaterbiodiversity.eu/ipt/[IPT de Biofresh], alojado por la Plataforma de Biodiversidad de Bélgica. Biofresh, es un proyecto internacional financiado por los EUA que tiene como objetivo construir una plataforma de información mundial para científicos y administradores de ecosistemas con acceso a todas las bases de datos disponibles que describen la distribución, el estado y las tendencias de la biodiversidad mundial de agua dulce. BioFresh integra las capacidades y la experiencia en biodiversidad de agua dulce de 19 instituciones de investigación.

== Datos marinos

http://www.iobis.org[OBIS] proporciona alojamiento de datos y servicio de asistencia técnica a publicadores de datos marinos de todo el mundo. EurOBIS/ Instituto Marino de Flandes (VLIZ) aloja múltiples instalaciones IPT que se pueden encontrar en http://ipt.vliz.be/ en nombre de varios Nodos OBIS. Actualmente, hay más de http://www.iobis.org/about/[20 Nodos OBIS] en todo el mundo que conectan a 500 instituciones de 56 países.

== Datos de vertebrados

http://vertnet.org/[VertNet] proporciona alojamiento de datos y servicio de asistencia técnica a publicadores de datos de especímenes y observaciones. Los datos alojados se pueden ver en http://ipt.vertnet.org/[IPT de VertNet]. Póngase en contacto con David Bloom <dbloom@vertnet.org> para obtener ayuda.

== Certificación

Al obtener el certificado, los repositorios pueden demostrar tanto a sus usuarios como a sus patrocinadores que una autoridad independiente los ha evaluado y respaldado su confiabilidad. El Sistema Mundial de Datos (WDS) y la Junta de Aprobación de Datos (DSA) han fusionado sus certificaciones de repositorios de datos en un conjunto de requisitos comunes estandarizados para la certificación de repositorios denominados https://goo.gl/fxVbgc[Core Trustworthy Data Repositories (Core TDR)]. La certificación requiere un repositorio de datos que proporcione evidencia de que son sostenibles y confiables. El repositorio primero realiza una autoevaluación interna, que luego es revisada por pares de la comunidad. Puede encontrar más información sobre el proceso de certificación https://zenodo.org/record/168411/files/Intro_To_Core_Trustworthy_Data_Repositories_Requirements_2016-11.pdf[aquí].
