= Preguntas frecuentes

Aquí encontrará respuestas a las preguntas más frecuentes acerca del IPT de GBIF. Por favor consulte el contenido de esta página antes de contactar al servicio de asistencia técnica de GBIF.

== Instalación

=== ¿Cuál es la mejor manera de migrar mi IPT a otro servidor sin perder ningún dato?

Hay un directorio importante que contiene toda la configuración y los recursos del IPT: el directorio de datos del IPT. Si se asegura de que se haga una copia de seguridad de este directorio con regularidad en algún lugar seguro, nunca perderá ningún dato.

Para migrar el IPT a otro servidor, solo asegúrese de copiar todo el contenido de el directorio de datos del IPT en el nuevo servidor. Es importante conservar los mismos permisos de la carpeta/archivo. Luego, xref:installation.adoc[instalar el IPT en el nuevo servidor], usando este directorio como el directorio de datos.

=== Mi instancia del IPT de GBIF es lenta. ¿Qué puedo hacer para mejorar el rendimiento? 

El Apache Tomcat viene con muy poca memoria asignada. Para aumentar el rendimiento, esta cantidad debe incrementarse dependiendo de la cantidad de memoria física en el servidor. Si el servidor tiene al menos 2 GB de RAM, la memoria disponible debe aumentarse a 1 GB. Para obtener más información sobre cómo hacerlo, consulte las http://wiki.apache.org/tomcat/FAQ/Memory[Preguntas frecuentes del Tomcat]

Se ejecuta lo siguiente:

----
export CATALINA_OPTS="-Xms512M -Xmx1024M -XX:PermSize=512M -XX:MaxPermSize=1024M"
----

=== Obtengo el siguiente error: "The data directory '/directory' is not writable." ¿Qué debo hacer?

Suponiendo que está ejecutando el Tomcat, debe asegurarse que el usuario que ejecuta el Tomcat tenga permisos en el directorio. Para averiguar el usuario que está ejecutando Tomcat en Linux, abra un shell e ingrese el siguiente comando:

----
$ ps waux | grep tomcat
----

Si el usuario es un "tomcatuser" y este usuario pertenece al grupo "tomcatgroup", cambie la propiedad del directorio de datos del IPT (y sus sub carpetas y archivos) ingresando el siguiente comando:

----
$ chown -R tomcatuser:tomcatgroup directory/
----

Para asegurarse de que solo este usuario tenga permiso de escritura, ingrese el siguiente comando:

----
$ chmod -R 755 directory/
----

En sistemas con seguridad de aislamiento, es posible que deba otorgar permisos al directorio. Por ejemplo, en Debian hay que añadir una anulación de SystemD:

----
$ systemctl edit syslog.service
[Service]
ReadWritePaths=/path/to/directory/
$ systemctl daemon-reload
$ systemctl restart tomcat8
----

Tenga en cuenta que si está ejecutando su IPT en el sistema operativo Windows, deberá verificar que su carpeta no haya vuelto a los permisos de solo lectura.

=== ¿Cómo puedo cambiar el idioma predeterminado del IPT?

El idioma por default del IPT es el inglés y no hay forma de cambiarlo en la interfaz de usuario.

Sin embargo, se puede cambiar fácilmente mediante la configuración manual. Para cambiar el idioma predeterminado del Inglés al Portugués por ejemplo, primero ubique el archivo `struts.properties` (si el IPT está instalado en Tomcat por ejemplo, debe ubicarse en `tomcat/webapps/ipt/WEB-INF/classes`). Luego actualice la propiedad `struts.locale` a:

----
struts.locale=pt
----

Reinicie el Tomcat y el IPT se iniciará en Portugués.

Tenga en cuenta que el código de idioma de dos letras debe coincidir con el código utilizado por el IPT. Los idiomas admitidos actualmente son portugués (`pt`), japonés (`ja`), francés (`fr`), español (`es`), chino tradicional (`zh`) y ruso (`ru`).

Tome en cuenta que cada vez que actualice a una nueva versión del IPT, deberá aplicar el mismo cambio.

=== ¿Cómo puedo cambiar el IPT del modo prueba al modo de producción?

El cambio del modo de prueba al modo de producción del IPT no se puede hacer automáticamente. Esto es por diseño, porque cada modo se conecta a un registro diferente (el modo de prueba utiliza el registro GBIF UAT mientras que el nodo de producción utiliza el registro GBIF Live). 

Por lo tanto, para cambiar al modo de producción, debe configurar una instancia IPT completamente nueva en modo de producción.

Para ahorrar tiempo en restablecer los recursos, puede intentar transferir sus recursos del modo de prueba al IPT de producción. Para hacer esto simplemente cargue un recurso IPT existente utilizando su carpeta de configuración de recursos comprimida. Las instrucciones completas sobre cómo hacer esto xref:manage-resources.adoc#upload-a-zipped-ipt-resource-configuration-folder[aquí].

=== ¿Qué conexiones de salida hace el IPT?

Durante la configuración y en modo de prueba, el IPT hace conexiones HTTPS seguras a https://gbrds.gbif-uat.org and https://tools.gbif.org.

Si se configura en modo de producción, el IPT hace conexiones HTTPS seguras a https://gbrds.gbif.org.

En ambos modos, el IPT hace conexiones HTTP normales a http://rs.gbif.org. Si instala vocabularios adicionales, el IPT los recuperará de raw.githubusercontent.com o de eol.org.

Recomendamos configurar su firewall para permitir el acceso saliente en los puertos 80 y 443 a todos los servidores GBIF: `130.225.43.0/24`.

Antes de la versión 2.3.4, las conexiones se realizaban mediante HTTP, en lugar de HTTPS a http://gbrds.gbif.org y http://gbrdsdev.gbif.org. Las conexiones HTTP usan el puerto 80.

=== ¿Cómo puedo configurar mi IPT para asignar DOI a los conjuntos de datos?

Para asignar DOI a los conjuntos de datos, el IPT debe configurarse con una cuenta DataCite, que a su vez se ha configurado para crear DOI bajo el dominio del IPT.

La cuenta de la organización titular ya debe estar asociada al IPT como una organización. Para obtener ayuda para asociar una organización a su IPT, puede consultar la sección xref:administration.adoc#agregar-organización[Agregar organización] del Manual del usuario.

Todo lo que queda es agregar la información de la organización a la cuenta DataCite (p. ej. el nombre de usuario, la contraseña, el prefijo, etc.) y asegurarse de que se haya marcado como "Cuenta activada". Para obtener ayuda para editar la organización y una descripción de cada campo en el formulario, puede consultar la sección xref:administration.adoc#edición-de-la-organización[Edición de la Organización] del manual de usuario.

Si trabaja para un nodo GBIF de algún país, contacte a mailto:helpdesk@gbif.org[GBIF Helpdesk] para solicitar información de cómo obtener una cuenta DataCite gratuita. GBIF tiene su propia cuenta DataCite y puede proveer a los nodos de los países una cuenta gratuita (determinándolo caso por caso). GBIF ha hecho esto para España y Colombia hasta el momento, ambos tienen un sólido historial de mantener su IPT en línea casi el 100% del tiempo.

Los siguientes IPT han sido configurados con cuentas DataCite, pueden asignar DOI a los conjuntos de datos y se reconocen como repositorio en BioSharing.org, que es usado por revistas como Nature para referir a sus autores a uno o mas repositorios que son adecuados para el tipo de datos que poseen.

* http://www.gbif.es/ipt/[GBIF España IPT] - https://biosharing.org/biodbcore-000854[Registro de BioSharing]
* http://data.canadensys.net/ipt/[IPT Canadensys] - https://biosharing.org/biodbcore-000855[Registro de BioSharing]
* http://ipt.biodiversidad.co/sib/[GBIF Colombia IPT] - https://biosharing.org/biodbcore-000856[Registro de BioSharing]

Los autores en España están depositados sus datos estandarizados en el IPT de GBIF España, p. ej. el siguiente conjunto de datos http://doi.org/10.15470/qomfu6 basado en este Descriptor de datos de datos científicos: http://doi.org/10.1038/sdata.2016.85

== Utilización

=== ¿Por qué los archivos publicados contienen líneas discontinuas?
El IPT no admite archivos de origen que tienen campos de varias líneas (campos que incluyen el carácter de nueva línea (`\n`) o de retorno de carro (`\r`)) incluso si ha especificado un carácter separador de campo (un carácter que delimita cada campo/columna en un renglón) en la configuración del origen. 

A menos que se eliminen estos caracteres de salto de línea, el IPT publicará archivos con líneas discontinuas (las columnas aparecerán mezcladas).

Para solucionar esto, puede eliminar estos caracteres de salto de línea del archivo origen, reemplace el archivo origen con el nuevo y vuelva a publicar el recurso. Recuerde que al cargar un archivo origen, puede decir al IPT que reemplace el archivo con uno nuevo siempre que ambos tengan el mismo nombre. De esa forma, no es necesario rehacer los mapeos.

=== ¿Por qué los archivos publicados no incluyen todos los registros?
Consulte la bitácora de la publicación para excepciones como:

----
java.sql.SQLException: Cannot convert value '0000-00-00 00:00:00' from column 65 to TIMESTAMP
----

esto quiere decir que tiene un valor de fecha no válido en su origen de datos, que en este caso es `0000-00-00 00:00:00`. 

Para resolver esto, puede actualizar el valor con "Null" y actualizar el recurso. Por lo general, puede basarse en el mensaje de la bitácora para identificar la columna de interés, como en el ejemplo anterior, dice "columna 65", que es la columna 65 en la fuente de datos.

El valor `0000-00-00 00:00:00` en su tabla SQL podría resultar al importar, mientras se ha mantenido la columna con "Not null" y el valor predeterminado como `0000-00-00 00: 00: 00`.

=== ¿Qué significa el error "No space left on device" y cómo lo soluciono?
Si encontró una excepción como:

----
Caused by: java.io.IOException: No space left on device
----

en su bitácora de publicación, significa que no queda espacio en la partición del disco que contiene su directorio de datos IPT.

Para solucionar esto, puede:

* Asignar más espacio a esta partición.
* Mover su directorio de datos IPT a otra partición donde haya mas espacio disponible. (Consulte las xref:installation.adoc[instrucciones de instalación] para cambiar la ubicación del directorio de datos).
* Liberar espacio en disco (por ejemplo, eliminar archivos temporales, eliminar aplicaciones no utilizadas, etc.)

=== ¿Cómo cambio la organización que publica mi recurso? El menú desplegable de la página de metadatos básicos está desactivado.
Tenga en cuenta que la organización que publica el recurso no se puede cambiar después de que el recurso se haya registrado en GBIF o se le haya asignado un DOI.

Para cambiar la organización que publica, debe volver a publicar el recurso y luego reestablecer la organización deseada. Para simplificar el proceso, puede volver a generar el conjunto de datos desde su carpeta de recursos IPT comprimida. Las instrucciones de como realizarlo se encuentran xref:manage-resources.adoc#upload-a-zipped-ipt-resource-configuration-folder[aquí].

Migrar el recurso desde la organización anterior que publica a la nueva organización siguiendo xref:manage-resources.adoc#migrate-a-resource[estas instrucciones]. Preste especial atención al paso 5, en el que deberá solicitar al servicio de asistencia de GBIF que actualice el Registro de GBIF.

Por último, puede eliminar el recurso antiguo utilizando la opción "Eliminar solo del IPT (huérfano)" en la página de edición del recurso.

=== ¿Cómo cambio el tipo de un recurso existente?

El tipo de un recurso se deriva de su mapeo con el estándar:

* Si el mapeo con el estándar es a {latest-dwc-occurrence}.xml[Extensión de registros de presencia de especies], el tipo es igual a "occurrence".
* Si el mapeo con el estándar es a {latest-dwc-taxon}.xml[Extensión del taxón], el tipo es igual a "checklist".
* Si el mapeo con el estándar es a {latest-dwc-event}.xml[Extensión de evento], el tipo es igual a "sampling-event".
* Si el mapeo con el estándar no es igual a alguno de los estándares predeterminados de el IPT (Occurrence, Taxon o Event), el tipo es igual a "other".

Por lo tanto, para cambiar el tipo de recurso, debe cambiar su mapeo con los términos. Para cambiar un recurso de tipo "occurrence" al tipo "checklist", por ejemplo, simplemente elimine todo el mapeo con los términos de la extensión "occurrence" y luego vuelva a crear el mapeo para los términos de "Taxon". Para finalizar el cambio se debe publicar una nueva versión del recurso. Si el recurso se ha registrado con GBIF, su tipo se actualizará automáticamente después de que se haya vuelto a publicar.

=== ¿Cuáles son algunos trucos para simplificar la creación y el mantenimiento de los metadatos?
Los conjuntos de datos pueden cambiar con el tiempo. Mantener los metadatos de los conjuntos de datos actualizados puede ser una carga, ya que las inconsistencias pueden comenzar a aparecer con el paso del tiempo. A continuación, se muestra una lista de trucos que puede utilizar para simplificar la creación de los metadatos y facilitar su mantenimiento a través del tiempo:

* use el ORCID de un contacto en lugar de proporcionar su correo electrónico y otros campos que son susceptibles al cambio si la persona cambia de trabajo. Para más información de cómo proporcionar un contacto ORCID consulte xref:manage-resources.adoc#basic-metadata[aquí].
* para conjuntos de datos que continúan cambiando/creciendo (versus conjuntos de datos estáticos) evite especificar recuentos exactos en descripciones textuales, p. ej. para registros o recuentos de taxones.
* utilice la cita del IPT xref:manage-resources.adoc#citations[Función de generación automática] en lugar de proporcionar una cita de los datos creada manualmente.
* utilice la importación del IPT por xref:manage-resources.adoc#taxonomic-coverage[Función de lista de taxón] en lugar de proporcionar cada taxón manualmente uno a uno al ingresar la cobertura taxonómica.

=== ¿Cómo cambio la organización de alojamiento de mi IPT?

WARNING: las instrucciones a continuación asumen que su IPT ya ha sido registrado e implican cambios manuales que requieren competencia técnica.

Primero, asegure que la organización de alojamiento deseada haya sido agregada a su IPT. Puede hacerlo a través de la interfaz de usuario. Para obtener ayuda para agregar una nueva organización a su IPT, consulte xref:administration.adoc#add-organization[esta sección] del manual de usuario. 

A continuación, realice los siguientes 2 cambios manuales en el archivo registration2.xml ubicado en el /config folder del directorio de datos de su IPT:

. {blank}
+
[source, xml]
----
<registration>
  <registry>
    <hostingOrganisation>
      <key>UUID de la deseada organización de alojo</key>
----

. {blank}
+
[source, xml]
----
<registration>
  <registry>
    <ipt>
      <organisationKey>UUID de la deseada organización de alojo</key>
----

Reiniciar Tomcat.

Por último presione el botón "actualizar registro" en la página de Edición del Registro de GBIF. Esto propagará el cambio hacia el Registro de GBIF. Para mayor información acerca de esta actualización, puede consultar xref:administration.adoc#edit-gbif-registration[esta sección] del manual de usuario. 

=== ¿Cómo restablezco la contraseña del administrador?

Si ha olvidado la contraseña del administrador, el administrador del servidor deberá restablecerla.

Usando un editor de texto, abra el archivo `config/users.xml` del directorio de datos del IPT. Busque el usuario administrador (con `role="Admin"`) y reemplace la contraseña encriptada con `VRRUXOTCtdCkQr40SrHdrnUJurTOYMW9`. Reinicie el IPT. A continuación puede iniciar como un usuario administrador con la contraseña `Ga_1bxiedrvNHSyK` — por supuesto, esta contraseña debe ser cambiada.

Si lo prefiere, un desarrollador de Java podría modificar la https://github.com/gbif/ipt/blob/master/src/test/java/org/gbif/ipt/utils/PBEEncryptTest.java[clase PBEEncryptTest] para generar un hash para una contraseña diferente, o desencriptar la contraseña olvidada (pero consulte https://github.com/gbif/ipt/issues/1460[issue 1460]).

=== ¿Cómo migro un conjunto de datos de una instalación de IPT a otra? 
Este proceso de migración debe realizarse directamente en el servidor siguiendo los siguientes pasos:

. Apague el servidor del IPT anterior; solo para asegurar que nadie hace ningún cambio.
. En el IPT anterior vaya a `/old-ipt-datadir/resources/[nombre_del_conjunto_de_datos]` y copie toda la carpeta del conjunto de datos
. En el IPT nuevo vaya a `/new-ipt-datadir/resources/` y pegue la carpeta del conjunto de datos
. Reinicie el nuevo servidor IPT
. Publique el conjunto de datos en el nuevo IPT (actualiza el punto terminal).

== Indexación por GBIF

=== ¿Cuánto tiempo tarda GBIF en comenzar a reindexar mi conjunto de datos?

La respuesta depende de la longitud de la cola de indexación de GBIF, del tamaño de su conjunto de datos y de si el servicio de indexación de GBIF está activado.

Normalmente GBIF tardará entre 5 y 60 minutos en comenzar la indexación de su conjunto de datos. Puede llevar varias horas terminar la indexación de grandes conjuntos de datos una vez que se inician (aquellos con varios millones de registros), así que tenga paciencia. En la parte inferior de la https://www.gbif.org/health[página GBIF de salud del sistema] se muestra la longitud de la cola de indexación, y la cola completa se puede visualizar en el https://registry.gbif.org/monitoring/running-crawls[Monitor de avance].

Si cree que GBIF no pudo indexar su conjunto de datos satisfactoriamente, envíe sus comentarios directamente a través de GBF.org, o envíe un correo electrónico al servicio de asistencia técnica de GBIF<helpdesk@gbif.org> para investigar lo que sucedió. Si está interesado en saber por qué es posible que GBIF no haya (re)indexado su conjunto de datos, consulte lo siguiente.

=== ¿Por qué GBIF no (re)indexó todavía mi conjunto de datos?

Eventualmente, GBIF apaga su servicio de indexación para mantenimiento (vea los enlaces en la pregunta anterior). Esta es la razón más frecuente de por qué los conjuntos de datos no son indexados tan rápido como se espera.

Si cree que GBIF no pudo indexar su conjunto de datos, envíe sus comentarios directamente a través de GBF.org, o envíe un correo electrónico al servicio de asistencia técnica de GBIF<helpdesk@gbif.org> para investigar lo que sucedió.

=== ¿Con qué frecuencia GBIF reindexa mis conjuntos de datos?

GBIF automáticamente intenta reindexar un conjunto de datos registrado cada vez que se actualiza su registro. Esto sucede cada vez que el conjunto de datos se vuelve a publicar a través del IPT.

Para atender a los conjuntos de datos no publicados mediante el IPT, GBIF automáticamente intenta reindexar cada 7 días todos los conjuntos de datos registrados.

NOTE: GBIF solo volverá a indexar un conjunto de datos si su última fecha de publicación ha cambiado desde la última vez que se indexó.

=== ¿Qué tipos de conjuntos de datos GBIF indexa/admite?

GBIF acepta 4 clases de conjunto de datos descritos xref:how-to-publish.adoc[aquí]. Actualmente, GBIF solo indexa los registros de presencia de especies, que pueden proporcionarse como registros del estándar o como registros de una extensión. En el caso de conjuntos de datos de eventos de muestreo, los registros de presencia de especies de una extensión serán ampliados con información que proviene desde su evento del estándar, siempre que sea posible.

=== ¿Por qué la cita de mi conjunto de datos es diferente en GBIF.org?

El IPT acepta citas de los conjuntos de datos en texto libre, sin embargo, estas se sobrescriben en la página del conjunto de datos en GBIF.org. Puede averiguar por qué en https://www.gbif.org/faq?q=citation[GBIF.org Preguntas frecuentes].
