= Agregar una nueva licencia

[WARNING]
--
Esta página contiene instrucciones de configuración sólo para usuarios IPT avanzados. Los conjuntos de datos publicados con una licencia diferente a las incluidas por GBIF no pueden ser publicadas en GBIF, o registradas en GBIF.

Recomendamos publicar un conjunto de datos con sólo metadatos en su lugar.
--

A partir de IPT v2.2, el IPT ofrece 3 licencias legibles por máquina para ser elegidas cuando se aplica una licencia a tu recurso:

* Dominio Público (CC0 1.0 técnicamente una renuncia)
* Atribución Creative Commons (CC-BY 4.0)
* Atribución no comercial Creative Commons (CC-BY-NC 4.0)

Cada licencia tiene una declaración de derechos por defecto asociada a esta que se muestra a los usuarios. Por ejemplo, si el publicador elige aplicar CC-BY a sus recursos, esta declaración de derechos mostrada a los usuarios es:

[quote]
Este trabajo es licenciado bajo una https://creativecommons.org/licenses/by/4.0/legalcode[licencia de Atribución Creative Commons (CC-BY) 4.0].

El listado de licencias y sus declaraciones de derechos pueden ser modificadas, sin embargo, lo cual es útil para las comunidades que necesitan aplicar diferentes licencias a sus recursos, o que quieren incluir instrucciones de uso adicionales.

Los pasos debajo explican como configurar el IPT con otra licencia para elegir.

== Instrucciones

Ubica el archivo licenses.properties, por ejemplo `/tomcat7/webapps/ipt/WEB-INF/classes/org/gbif/metadata/eml/licenses.properties`. Abra el archivo en un editor de texto, y haga lo siguiente:

. Agregue una nueva propiedad definiendo el nombre de la licencia usando el siguiente formato:
+
----
license.name.<prefix>=Nombre
# Por ejemplo:
license.name.odcby=Licencia de Atribución Open Data Commons (ODC-By) 1.0
----

. Agregue una nueva propiedad definiendo la declaración de derechos de la licencia usando el siguiente formato:
+
----
license.text.<prefix>=Texto
# Por ejemplo:
license.text.odcby=Este trabajo es licenciado bajo una <a href="http://www.opendatacommons.org/licenses/by/1.0">Licencia de atribución Open Data Commons (ODC-By) 1.0</a>.
----

. Doble verificación
.. el _prefijo_ de ambas llaves coincide,
.. un ancho de HTML define el nombre de la licencia y la URL es incluida en el texto ya que esto es lo que hace que sea legible por la máquina de licencias,
.. el nombre usado en el ancho HTML es el mismo nombre que es usado en la propiedad anterior.
. Haga una copia de respaldo del archivo licenses.properties, ya que será sobrescrito la próxima vez que actualice su IPT
. Reinicie su contenedor de servlet (por ejemplo, Tomcat) para que la nueva configuración surta efecto
