= Versiones

[TIP]
.Últimas versiones estables
====
The current, stable release is version <<2-5-1-september-2021,2.5.1>>.

You are reading the manual for version {page-version}. You can read other versions of the manual using the selectors at the top-right or bottom-left of the screen.
ifeval::["{language}",  != "en"]
Note that the not all manual versions are available in TRANSLATOR_PUT_YOUR_LANGUAGE_HERE.
endif::[]
====


== *2.5.1* – September 2021

* https://repository.gbif.org/content/groups/gbif/org/gbif/ipt/2.5.1/ipt-2.5.1.war[Download WAR], xref:installation.adoc#installation-from-linux-packages[Linux packages] or xref:installation.adoc#installation-from-docker[use Docker]
* xref:2.5@release-notes.adoc[IPT v2.5.1 Release Notes]
* xref:2.5@index.adoc[Manual del Usuario]
* Addressed https://github.com/gbif/ipt/milestone/28?closed=1[4 issues].
* Traducida en 7 idiomas

Existing users should upgrade to this version following the instructions in the xref:2.5@release-notes.adoc[Release Notes]. New users should follow the xref:getting-started.adoc[Getting Started guide].

This version addresses a bug introduced in version 2.5.0, which prevented the IPT from connecting to database sources. Users who connect the IPT to database sources will need to upgrade to 2.5.1.

No release date has been set for the next release. Progress working on issues for the next release can be browsed https://github.com/gbif/ipt/milestones[on GitHub].

Los problemas menores y los asuntos de seguridad se abordarán en parches para las diferentes versiones.

== *2.5.0* – August 2021

* xref:2.5@release-notes.adoc[Notas de la Versión IPT v2.5.0]
* xref:2.5@index.adoc[Manual del Usuario]
* Addressed https://github.com/gbif/ipt/milestone/27?closed=1[81 issues].
* Traducida en 7 idiomas

Existing users should upgrade to this version following the instructions in the xref:2.5@release-notes.adoc[Release Notes]. New users should follow the xref:getting-started.adoc[Getting Started guide].

This version addresses 81 issues, including the famous "double log in bug", and brings in a fresher-looking user interface. This user manual has also been refreshed, enabling a complete translation into Spanish.

== *2.4.2* - Septiembre de 2020

* xref:2.4@release-notes.adoc[Notas de la versión IPT v2.4.2]
* xref:2.4@index.adoc[Manual de Usuarios]
* Abordada https://github.com/gbif/ipt/milestone/9?closed=1[1 incidencia].
* Traducida en 7 idiomas

La versión 2.4.2 soluciona una vulneración menor de la seguridad en Apache Struts, que utiliza el IPT. Los usuarios deberían planificar una actualización de esta versión siguiendo las instrucciones de las xref:2.4@release-notes.adoc[Notas de la Versión]. También se ha incluido una mejora para el uso de memoria cuando se leen conjuntos de datos grandes desde un servidor PostgreSQL.

== *2.4.1* - Septiembre de 2020

* xref:2.4@release-notes.adoc[Notas de la Versión IPT v2.4.1]
* xref:2.4@index.adoc[Manual de Usuarios]
* Abordadas https://github.com/gbif/ipt/milestone/25?closed=1[12 incidencias].
* Traducida en 7 idiomas

La versión 2.4.1 soluciona una vulneración de la seguridad en Apache Struts, que utiliza el IPT. Los usuarios deberían planificar una actualización de esta versión siguiendo las instrucciones de las xref:2.4@release-notes.adoc[Notas de la Versión].

== *2.4.0* – Julio de 2019

* xref:2.4@release-notes.adoc[Notas de la Versión del IPT v2.4.0]
* xref:2.4@index.adoc[Manual de Usuarios]
* Abordadas https://github.com/gbif/ipt/milestone/8?closed=1[19 incidencias]. 
* Traducida en 7 idiomas

La versión 2.4.0 soluciona vulneraciones de seguridad en Apache Jackson y Apache Struts, que utiliza el IPT. Los usuarios deberían planificar una actualización de esta versión siguiendo las instrucciones de las xref:2.4@release-notes.adoc[Notas de la Versión]. También se actualiza la integración para DOIs personalizados desde DataCite, y elimina el soporte para DOIs (sin uso) de EZID. El número de versión ha sido actualizado a 2.4.0 para reflejar la eliminación del soporte para EZID.

== *2.3.6* - Julio de 2018

* xref:2.4@release-notes.adoc[Notas de la versión IPT v2.3.6]
* https://github.com/gbif/ipt/wiki/IPTManualNotes.wiki[Manual de Usuarios] https://github.com/gbif/ipt/wiki/IPT2ManualNotes_ES.wiki[(es)]
* Abordadas https://github.com/gbif/ipt/milestone/7?closed=1[20 incidencias].
* Traducida en 7 idiomas

La versión 2.3.6 soluciona una vulneración de seguridad en JQuery, que utiliza el IPT. Los usuarios deberían planificar una actualización de esta versión siguiendo las instrucciones de las xref:2.4@release-notes.adoc[Notas de la Versión].

https://github.com/gbif/ipt/issues/1411[Una incidencia] permanece con DOIs personalizados de DataCite. Si fuese necesario, se lanzará otra versión del IPT en julio o agosto.

== *2.3.5* – Octubre de 2017

* xref:2.4@release-notes.adoc[Notas de la Versión IPT v2.3.5]
* https://github.com/gbif/ipt/wiki/IPTManualNotes.wiki[Manual de Usuarios] https://github.com/gbif/ipt/wiki/IPT2ManualNotes_ES.wiki[(es)]
* Abordadas https://github.com/gbif/ipt/projects/3[27 incidencias]: 6 Defectos, 7 Mejoras y 15 de Otro tipo
* Traducida en 7 idiomas

La versión 2.3.4 soluciona una https://struts.apache.org/docs/s2-045.html[vulnerabilidad de seguridad] que fue descubierta en el marco de trabajo web de Apache Struts, que utiliza el IPT. Esta vulneración afecta a todas las versiones del IPT, incluyendo la 2.3.3, por ello todos los usuarios deberían planificar una actualización de esta versión inmediatamente siguiendo las instrucciones de las xref:2.4@release-notes.adoc[Notas de la Versión].

== *2.3.4* - Marzo de 2017

* xref:2.4@release-notes.adoc[Notas de la Versión IPT v2.3.4]
* https://github.com/gbif/ipt/wiki/IPTManualNotes.wiki[Manual de Usuarios] https://github.com/gbif/ipt/wiki/IPT2ManualNotes_ES.wiki[(es)]
* Abordadas https://github.com/gbif/ipt/projects/3[6 incidencias]: 3 Defectos, 2 Mejoras y 1 de Otro tipo
* Traducida en 7 idiomas

La versión 2.3.4 soluciona una https://struts.apache.org/docs/s2-045.html[vulnerabilidad de seguridad] que fue descubierta en el marco de trabajo web de Apache Struts, que utiliza el IPT. Esta vulneración afecta a todas las versiones del IPT, incluyendo la 2.3.3, por ello todos los usuarios deberían planificar una actualización de esta versión inmediatamente siguiendo las instrucciones de las xref:2.4@release-notes.adoc[Notas de la Versión].

== *2.3.3* - Diciembre de 2016

* xref:2.4@release-notes.adoc[Notas de la Versión IPT v2.3.3]
* https://github.com/gbif/ipt/wiki/IPTManualNotes.wiki[Manual de Usuarios] https://github.com/gbif/ipt/wiki/IPT2ManualNotes_ES.wiki[(es)]
* Abordadas https://github.com/gbif/ipt/projects/1[88 incidencias]: 22 Defectos, 17 Mejoras, 36 No se Solucionan, 10 Duplicados y 3 de Otro tipo
* Traducida en 7 idiomas

En https://gbif.blogspot.com/2017/01/ipt-v233-your-repository-for.html[esta entrada del blog] se describen las nuevas características añadidas al IPT en la versión 2.3.3. Además, tenga en cuenta, por favor, que GBIF lanzó recientemente un nuevo conjunto de modelos de Microsoft Excel para la carga de datos en el IPT. Los nuevos modelos proporcionan una solución más simple para la captura, formateo y subida de los tres tipos de datos de GBIF: xref:sampling-event-data.adoc[datos de eventos de muestro], xref:occurrence-data.adoc[datos de presencias de especies], y xref:checklist-data.adoc[datos de listados de especies]. Se puede encontrar más información sobre estos modelos en https://www.gbif.org/newsroom/news/new-darwin-core-spreadsheet-templates[esta noticia].

== *2.3* - Septiembre de 2015

* xref:2.4@ipt-release-notes-2_3.adoc[Notas de la Versión IPT v2.3]
* https://github.com/gbif/ipt/wiki/IPTUserManualv23.wiki[Manual de Usuarios] https://github.com/gbif/ipt/wiki/IPT2ManualNotes_ES.wiki[(es)]
* Abordadas https://github.com/gbif/ipt/milestone/20?closed=1[38 incidencias]: 15 Defectos, 15 Mejoras, 4 No se Solucionan y 4 que fueron consideradas como Tareas
* Traducida en 6 idiomas

== *2.2* - Marzo de 2015

* xref:2.4@ipt-release-notes-2_2.adoc[Notas de la Versión IPT v2.2]
* https://github.com/gbif/ipt/wiki/IPTUserManualv22.wiki[Manual de Usuarios]
* https://gbif.blogspot.com/2015/03/ipt-v22.html[Anuncio del Lanzamiento]
* Abordadas https://github.com/gbif/ipt/milestone/18?closed=1[74 incidencias]: 20 Defectos, 26 Mejoras, 16 No se Solucionan, 6 Duplicados, 2 de Otro tipo, 1 Tarea y 3 que fueron consideradas Invalidas
* Traducida en 6 idiomas

== *2.1* - Abril de 2014

* xref:2.4@ipt-release-notes-2_1.adoc[Notas de la Versión IPT v2.1]
* https://github.com/gbif/ipt/wiki/IPTUserManualv21.wiki[Manual de Usuarios]
* https://gbif.blogspot.com/2014/04/ipt-v21.html[Anuncio del Lanzamiento]
* Abordadas https://github.com/gbif/ipt/milestone/16?closed=1[85 incidencias]: 38 Defectos, 11 Mejoras, 18 No se Solucionan, 6 Duplicados, 1 de Otro tipo y 11 que fueron considerados Invalidos
* Traducida en 6 idiomas (añadida traducción al japonés)

== *2.0.5* - Mayo de 2013

* xref:2.4@ipt-release-notes-2_0_5.adoc[Notas de la Versión IPT v2.0.5]
* https://github.com/gbif/ipt/wiki/IPTUserManualv205.wiki[Manual de Usuarios]
* https://gbif.blogspot.com/2013/05/ipt-v205-released-melhor-versao-ate-o.html[Anuncio del Lanzamiento]
* Abordadas https://github.com/gbif/ipt/milestone/14?closed=1[45 incidencias]: 15 Defectos, 17 Mejoras, 2 Parches, 7 No se Solucionan, 3 Duplicados y 1 que fue considerada Invalida
* Traducida en 5 idiomas (añadida traducción al portugués)

== *2.0.4* - Octubre de 2012

* xref:2.4@ipt-release-notes-2_0_4.adoc[Notas de la Versión IPT v2.0.4]
* https://github.com/gbif/ipt/wiki/IPTUserManualv204.wiki[Manual de Usuarios]
* https://gbif.blogspot.com/2012/10/ipt-v204-released.html[Anuncio del Lanzamiento]
* Abordadas https://github.com/gbif/ipt/milestone/13?closed=1[108 incidencias]: 38 Defectos, 35 Mejoras, 7 de Otro tipo, 5 Parches, 18 No se Solucionan, 4 Duplicados y 1 que fue considerada como Invalida
* Traducida en 4 idiomas (añadida traducción a chino tradicional)

== *2.0.3*  Noviembre de 2011

* xref:2.4@ipt-release-notes-2_0_3.adoc[Notas de la Versión IPT v2.0.3]
* https://github.com/gbif/ipt/wiki/IPTUserManualv203.wiki[Manual de Usuarios]
* https://gbif.blogspot.com/2011/11/important-quality-boost-for-gbif-data.html[Anuncio del Lanzamiento]
* Abordadas https://github.com/gbif/ipt/milestone/12?closed=1[85 incidencias]: 43 defectos, 31 Mejoras, 3 Parches, 7 No se Solucionan y 1 Duplicado
* Traducida en 3 idiomas (añadidas traducciones a francés y español)

== *2.0.2* – June 2011

* https://lists.gbif.org/pipermail/ipt/2011-June/000352.html[Release Announcement]

== *2.0.1* – February 2011

* First IPT version 2 release
* https://lists.gbif.org/pipermail/ipt/2011-February/000309.html[Release Announcement]
