= Notas de la Versión

*Versiones IPT: pass:[2.5.*]*

== Instrucciones de actualización

WARNING: Asegúrese de *realizar copia de seguridad del directorio de datos del IPT antes de ejecutar una actualización*. Según los xref:data-hosting-centres.adoc#data-hosting-centre-criteria[Criterios de los Centros de Alojamiento de Datos], se recomienda encarecidamente realizar copias de seguridad programadas para los directorios de datos del IPT en general. 

CAUTION: Una vez que el IPT ha sido actualizado a 2.3.x o posterior desde la versión 2.2 o anterior, no será posible volver a una versión anterior debido a cambios en la configuración de los archivos del IPT.

Compruebe que su sistema reúne los xref:requirements.adoc[requisitos de instalación] para esta versión.

El método de actualización depende del xref:installation.adoc#installation-method[método de instalación] original.

=== Actualizaciones utilizando paquetes Linux

Los usuarios de paquetes Linux en Red Hat, CentOS, Debian, Ubuntu, etc. pueden realizar la actualización utilizando el gestor de paquetes del sistema.

[source, shell]
----
# Red Hat, CentOS etc:
yum update ipt
# Debian, Ubuntu etc:
apt install ipt
----

Estos comandos se pueden usar para probar una versión anterior en Red Hat/CentOS:

[source, shell]
----
# Asegurarse de que la configuración del repositorio GBIF está actualizada:
yum-config-manager --add-repo https://packages.gbif.org/gbif.repo

# Instalar la última versión testada:
yum install --enablerepo=gbif-testing ipt

# Volver a una versión anterior estable:
yum downgrade ipt-2.4.2

# Mostrar todas las versiones disponibles, testadas y estables:
yum --showduplicates list --enablerepo=gbif-testing ipt
----


=== Actualizaciones utilizando un contenedor de servlet

TIP: When upgrading to version 2.5.0 or later, follow xref:installation.adoc#tomcat[step 2] of the installation instructions to set a data directory location. You will no longer need to reconfigure the data directory each time you upgrade the IPT.

Una actualización se puede ejecutar en 4 pasos:

. Realice una copia de seguridad del directorio de datos existente y de cualquier xref:customization.adoc[estilo personalizado] (imágenes, hojas de estilo, etc.) antes de actualizar su IPT.
. Reemplace el archivo .war anterior con la última edición pero mantenga el mismo nombre (ej.: `ipt.war`).
+
NOTE: Si reemplaza el archivo .war mientras Tomcat está apagado, asegúrese de eliminar el directorio expandido asociado antes de reiniciar Tomcat, para que el archivo WAR actualizado aparezca expandido de nuevo cuando inicie Tomcat.

. (Si el directorio de datos no está configurado con Tomcat). Abra inmediatamente el IPT en un buscador web y reutilice el directorio de datos existente en la página de opciones del IPT inicial
. Para asegurarse de que la actualización funcione, intente iniciar sesión busque el número de la nueva versión en el pie de página. (_Reinicie Tomcat si aún aparece la versión anterior._)
. Vuelva a aplicar su estilo personalizado (si aplica)

=== Actualizaciones utilizando Docker

Vea las instrucciones de xref:installation.adoc#installation-using-docker[instalación utiliando Docker]. En general, la etiqueta `latest` apuntará a la versión actual estable.

== Instrucciones para después de la actualización

Following the upgrade, a warning message may appear indicating that some resources failed to load. This is caused when an old resource is missing required metadata after not being republished for a long time. Resource managers can fix this problem by re-publishing the affected resources.

Una novedad en el IPT 2.3.x es la capacidad para publicar datos basados en muestras. Una vez que la actualización se ha completado, el administrador del IPT debe instalar el núcleo de Eventos Darwin Core. Tenga en cuenta que el núcleo de Eventos Darwin Core está instalado por defecto en las instalaciones nuevas.

Adicionalmente, el administrador del IPT debería actualizar todos los ficheros centrales y extensiones a sus últimas versiones. Esto permitirá a los publicadores la ventaja de tener los nuevos términos y vocabularios incluidos en las últimas versiones.

== Cambios importantes en esta versión

La lista completa de características nuevas está documentada en la xref:releases.adoc[página de la versión]. Por favor, preste especial atención a estos puntos después de actualizar: 

* IPT 2.5.1 includes a bugfix to connect to database sources, but it otherwise identical to version 2.5.0.
* El IPT 2.5.0 incluye concectores de bases de datos (bibliotecas JDBC) actualizados para MySQL, PostgreSQL, MS SQL Server, Sybase y Oracle. Por favor, compruebe que las configuraciones de su base de datos aún funciona.
* IPT 2.5.0 now includes a troubleshooting page, with full details accessible only to administrators, accessible from the main menu.
* El IPT 2.5.0 puede ahora leer una ubicación de directorio de datos desde un contenedor servlet, vea el xref:installation.adoc#tomcat[paso 2] de las instrucciones de instalación.
* El IPT 2.5.0 ya no es compatible con Microsoft Internet Explorer. (El propio Microsoft https://blogs.windows.com/windowsexperience/2021/05/19/the-future-of-internet-explorer-on-windows-10-is-in-microsoft-edge/[ya no es compatible con MSIE] para sus servidores online MS365.)
* The documentation has moved to this new location; links have been made from the old GitHub Wiki.
* xref:customization.adoc[Customization] (styling etc) using `custom.css` is broken in this release, see this https://github.com/gbif/ipt/issues/1634[issue].

Si está actualizando desde una versión anterior a la 2.4, por favor, consulte las notas de la xref:2.4@release-notes.adoc[versión antigua].

== Cuando todo lo demás falla

Explore las xref:faq.adoc[FAQ], que continúan siendo actualizadas con buenas preguntas, o pregunte en la https://lists.gbif.org/mailman/listinfo/ipt/[lista de mailing del IPT].
